### ISSUE TITLE
导出文件的 item_id 数据类型有误

### ISSUE THREAD

**Issue by ad030405** [NOWorEVER/UIGF2.2--UIGF-4#1]
UIGF 4.0要求的 `item_id` 数据类型为 `string`，但转换后的 json 文件中 `item_id` 的数据类型为 `number`，如下图：
<img width="770" alt="Snipaste_2024-08-07_01-36-11" src="https://github.com/user-attachments/assets/05592423-c5a6-4291-b901-4a64af318fd7">
使用 UIGF 4.0 官方校验工具结果如下：
<img width="1275" alt="Snipaste_2024-08-07_01-37-00" src="https://github.com/user-attachments/assets/757aa98b-888d-4574-b8bf-633c5cf73f14">
代码内嵌的数据字典中，物品 id 的 python 数据类型也为 `int`：
<img width="770" alt="Snipaste_2024-08-07_01-41-56" src="https://github.com/user-attachments/assets/46cbda33-bd51-419d-8f06-945a1c9d3312">
---
> 我觉得这个锅可能要 UIGF 那边来背，因为他们的官方翻译 API 调用后得到的 `item_id` 和他们提供的字典 json 文件中的物品 id 也全是数字类型，但 4.0 标准确实要求用 `string`，要用的话还要做数据类型转换。

**Comment by NOWorEVER** [comment]
没啥问题，加个str就行😂，晚点看看，谢谢
